
import React from 'react';
import { ArrowLeft, ChevronDown, ChevronUp } from 'lucide-react';

interface FAQProps {
  onBack: () => void;
}

const QUESTIONS = [
  {
    q: "Is Infrano Tools free to use?",
    a: "Yes. The entire arsenal is free to use. We support the infrastructure costs through non-intrusive advertisements."
  },
  {
    q: "Do you save my images or text?",
    a: "No. All processing happens either client-side or through secure, stateless API calls. We do not store any user inputs."
  },
  {
    q: "Why did my download fail?",
    a: "The demons of the internet (CORS policies) or platform API rate limits can sometimes block requests. Try again in a few moments or check if the link works in a private tab."
  },
  {
    q: "Can I use the generated images commercially?",
    a: "Images generated by Gemini AI generally allow for broad usage, but you should consult Google's Generative AI terms of service for specific commercial rights."
  },
  {
    q: "How accurate is the AI?",
    a: "We utilize Google's Gemini 2.5 Flash, which is highly capable. However, AI can hallucinate. Always verify critical information, especially code and facts."
  }
];

export const FAQ: React.FC<FAQProps> = ({ onBack }) => {
  const [openIndex, setOpenIndex] = React.useState<number | null>(0);

  return (
    <div className="max-w-3xl mx-auto animate-fade-in-up pb-10">
      <button 
        onClick={onBack}
        className="flex items-center text-sm text-gray-500 hover:text-demon-neon transition-colors mb-6 group"
      >
        <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
        Back to Arsenal
      </button>

      <h2 className="text-3xl md:text-4xl font-bold font-brand text-white mb-8 text-center uppercase tracking-wider">
        Frequently Asked <span className="text-demon-neon">Questions</span>
      </h2>

      <div className="space-y-4">
        {QUESTIONS.map((item, idx) => (
          <div 
            key={idx}
            className="glass-card rounded-xl border border-gray-800 overflow-hidden transition-all duration-300"
          >
            <button 
              onClick={() => setOpenIndex(openIndex === idx ? null : idx)}
              className="w-full flex justify-between items-center p-5 text-left bg-black/20 hover:bg-black/40 transition-colors"
            >
              <span className="font-bold text-gray-200">{item.q}</span>
              {openIndex === idx ? <ChevronUp className="text-demon-neon" /> : <ChevronDown className="text-gray-500" />}
            </button>
            
            <div 
              className={`px-5 text-gray-400 text-sm leading-relaxed overflow-hidden transition-all duration-300
                ${openIndex === idx ? 'max-h-40 py-5 opacity-100' : 'max-h-0 py-0 opacity-0'}
              `}
            >
              {item.a}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
